const foods = [
  {
    category: "meal",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "protein",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "salad",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "swallow",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "meal",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "protein",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "salad",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "swallow",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "meal",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "protein",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "salad",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "swallow",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "meal",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "protein",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "salad",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "swallow",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "meal",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "protein",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "salad",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "swallow",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "Pepper Soup",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "Pepper Soup",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "Drinks",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
  {
    category: "Drinks",
    image: "/jollofrice.JPG",
    title: "Jollof rice with sauce",
    description: "Jollof rice and sauce and mixed with egg and one beef",
    price: 2300,
  },
];

export default foods;
